name: flutter_data_layer_sample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.4
  intl: 0.17.0
  logger: 1.1.0
  path: 1.8.0
  path_provider: 2.0.9
  provider: 6.0.2
  sqflite: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2

flutter:
  uses-material-design: true